#!/usr/bin/env bash
# 4-TCP_and_UDP_ports
# Display listening TCP, UDP, and UNIX sockets with PID/program

# TCP and UDP listening sockets (Internet)
echo "Active Internet connections (only servers)"
netstat -tulnp

# UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
netstat -xlnp
