#!/usr/bin/env bash
# 5-is_the_host_on_the_network
# Pings an IP address passed as an argument

# Check if an argument was provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the IP 5 times
ping -c 5 "$1"
